### PR TITLE
UX/UI changes to NewSiteForm

### PR DESCRIPTION
**Pull request by callumu21**
1. Users can click on the map when choosing a location to drop a pin for the coordinates
2. Users can press Back on the map view, preserving the state of the marker to its set position
3. Users can press Save Site Location to store the marker coordinates
4. Users pressing Reset on the form will remove any stored coordinates/marker position
5. Upon pressing Save Site Location with a marker placed down, the button turns green, signifying a location has been saved
6. Users can upload only an image, rather than any file type, from their device
7. An image display now shows users the image they have selected
8. Pressing reset removes the stored image and defaults to the camera icon
9. Removed console.logs
10. Added followsUserLocation={true} to the main map display for users so that the map will track their movement automatically

### CODE REVIEW

**Comment by MattArwenLangham** [comment]
_2. Users can press Back on the map view, preserving the state of the marker to its set position_

Errors out when trying this on my device.


Also, I'd add that a website isn't necessarily a required field.

Apart from those comments, this is really great stuff! Added a lot more intuitiveness and UX to the forms. Well done Callum and Waqas :smile:

**Comment by callumu21** [comment]
1. Added ternary operator to deal with resetting the marker upon pressing the back button if no marker coordinates exist in state. Rather than setting the marker to null, it now just toggles the overlay.

**Review by MattArwenLangham — APPROVED** [review]
Tested and all works now :)

**Review by BrennB99 — APPROVED** [review]
Works well on ios. Nice one!

**Pull request merged**
